version: '3.8'

services:
  web:
    build: .
    container_name: career-coach-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: career-coach-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/www/certbot:/var/www/certbot  # Certbot challenge 볼륨
    depends_on:
      - web
