version: '3.8'

services:
  web:
    build: .
    expose:
      - "8000"  # 내부 포트만 노출
    environment:
      - DJANGO_SETTINGS_MODULE=career_coach.settings
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # SQLite DB 파일 마운트 (데이터 보존)
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # 외부 80포트로 서비스
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: unless-stopped
