# Generated by Django 5.2.5 on 2025-08-16 09:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_summary', models.TextField(help_text='예: 3년차 백엔드 개발자', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='경력 요약')),
                ('job_role', models.CharField(help_text='예: Spring Boot/MSA 기반 커머스 서비스 개발', max_length=100, verbose_name='수행 직무')),
                ('technical_skills', models.TextField(help_text='예: Python, AWS EC2, Docker, MySQL', verbose_name='기술 스킬')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='총 경력 연수')),
                ('analysis_result', models.JSONField(blank=True, null=True, verbose_name='AI 분석 결과')),
            ],
            options={
                'verbose_name': '이력서 프로필',
                'verbose_name_plural': '이력서 프로필들',
                'db_table': 'resume_profiles',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_goal', models.CharField(choices=[('skill_enhancement', '기술 스킬 강화'), ('career_change', '커리어 전환'), ('promotion', '승진/성장'), ('interview_prep', '면접 준비')], default='skill_enhancement', max_length=100)),
                ('learning_roadmap', models.JSONField(help_text='단계별 학습 계획', verbose_name='학습 로드맵')),
                ('estimated_duration_months', models.PositiveIntegerField(default=3, verbose_name='예상 완료 기간(개월)')),
                ('generation_metadata', models.JSONField(default=dict, verbose_name='생성 메타데이터')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='chatbot.resumeprofile')),
            ],
            options={
                'verbose_name': '학습 경로',
                'verbose_name_plural': '학습 경로들',
                'db_table': 'learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_company_type', models.CharField(choices=[('startup', '스타트업'), ('midsize', '중견기업'), ('large', '대기업'), ('foreign', '외국계')], default='startup', max_length=50)),
                ('target_position_level', models.CharField(choices=[('junior', '주니어'), ('mid', '미드레벨'), ('senior', '시니어'), ('lead', '리드/매니저')], default='junior', max_length=50)),
                ('questions', models.JSONField(help_text='5개의 맞춤형 면접 질문', verbose_name='생성된 면접 질문들')),
                ('generation_metadata', models.JSONField(default=dict, help_text='프롬프트 정보, 소요시간 등', verbose_name='생성 메타데이터')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='chatbot.resumeprofile')),
            ],
            options={
                'verbose_name': '면접 세션',
                'verbose_name_plural': '면접 세션들',
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_type', models.CharField(choices=[('interview_quality', '면접 질문 품질'), ('learning_path_relevance', '학습 경로 적합성'), ('overall_satisfaction', '전체 만족도')], max_length=50)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='평점 (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='상세 피드백')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot.resumeprofile')),
            ],
            options={
                'verbose_name': '사용자 피드백',
                'verbose_name_plural': '사용자 피드백들',
                'db_table': 'user_feedbacks',
            },
        ),
    ]
